backend/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


# Importa tus viewsets aquí
# from api.views.auth import RegisterView, LoginView, LogoutView, ProfileView
# from api.views.plans import PlanViewSet
# from api.views.classes import ClassViewSet
# from api.views.messages import MessageViewSet

router = DefaultRouter()
router.register(r'plans', views.PlanViewSet, basename='plan')
router.register(r'push_tokens', views.ClientPushTokenViewSet, basename='push_tokens')
# router.register(r'classes', ClassViewSet, basename='class')
# router.register(r'messages', MessageViewSet, basename='message')

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('create_checkout_link/', views.create_checkout_link, name='create_checkout_link'),
    path('user/dashboard/', views.user_dashboard, name='user_dashboard'),
    path('company_info/', views.company_info, name='company_info'),
    path('classes/', views.classes, name='classes'),
    path('reservations/', views.reservations, name='reservations'),
    path('reservations/<int:id>/check_in/', views.reservation_check_in, name='reservation_check_in'),
    path('reservations/<int:id>/cancel/', views.reservation_cancel, name='reservation_cancel'),
    path('account/reservations/', views.account_reservations, name='account_reservations'),
    path('sessions/<int:activity_session_id>/book/', views.activity_session_book, name='activity_session_book'),
    path('sessions/<int:activity_session_id>/waitlist/', views.activity_session_waitlist, name='activity_session_waitlist'),

    # Rutas automáticas de los routers (planes, clases, mensajes, etc.)
    path('', include(router.urls)),
]

backend/backend/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('', include('core.urls')),
    path("activities/", include("activities.urls", namespace="activities")),
    path("staff/", include("staff.urls", namespace="staff")),
    path("clients/", include("clients.urls", namespace="clients")),
    path("plans/", include("plans.urls", namespace="plans")),
    path("payments/", include("payments.urls", namespace="payments")),
    path("locations/", include("locations.urls", namespace="locations")),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    # path('sh/', include('sh.urls')),
]

backend/clients/urls.py
app_name = "clients"

from django.urls import path
from . import views

urlpatterns = [
    path("clients/", views.clients, name="clients"),
    path("client/", views.client, name="client"),
    path("client/<int:pk>/", views.client, name="client"),
    path("delete_client/<int:pk>/", views.delete_client, name="delete_client"),
    path("save_client_plan_payment/<int:client_plan_pk>/", views.save_client_plan_payment, name="save_client_plan_payment"),
    path("get_client_plan_payment_form/<int:client_plan_pk>/", views.get_client_plan_payment_form, name="get_client_plan_payment_form"),
]

backend/clients/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.functional import cached_property
from core.models import BaseModel
from datetime import date
from django.utils import timezone
from plans.models import Plan

User = get_user_model()

class Client(BaseModel):
    source = models.CharField(max_length=100, null=True, choices=[('admin_panel', 'Admin panel'), ('mobile_app', 'App móvil')])
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True)
    birth_date = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ['first_name', 'last_name']

    def __str__(self):
        return f"{self.first_name} {self.last_name}".strip()

    @cached_property
    def user_obj(self):
        return User.objects.get(pk=self.user_id)
    
    def get_full_name(self):
        return self.user_obj.get_full_name()

    def get_age(self):
        if not self.birth_date:
            return None
        today = date.today()
        age = today.year - self.birth_date.year
        # Ajuste si aún no ha llegado el cumpleaños este año
        if (today.month, today.day) < (self.birth_date.month, self.birth_date.day):
            age -= 1
        return age
    
    @cached_property
    def current_plan(self):
        return self.plans.prefetch_related("plan").filter(is_active=True).first()
    
    def get_plans_history(self):
        current_plan_id = None
        if self.current_plan:
            current_plan_id = self.current_plan.id

        return self.plans.exclude(
            is_active=False,
            cancelled_at__isnull=True,
        ).exclude(id=current_plan_id).prefetch_related("plan")

class ClientPlan(BaseModel):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name="plans")
    plan = models.ForeignKey(Plan, on_delete=models.PROTECT, related_name="client_plans")

    purchase_date = models.DateField(auto_now_add=True)
    first_use_date = models.DateField(null=True, blank=True)

    remaining_sessions = models.PositiveIntegerField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

    cancelled_at = models.DateTimeField(null=True)
    cancelled_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    cancellation_comments = models.CharField(max_length=255, null=True)
    stripe_session_id = models.CharField(max_length=1000, null=True)

    class Meta:
        verbose_name = "Client Plan"
        verbose_name_plural = "Client Plans"
        ordering = ["-id"]

    def __str__(self):
        return f"{self.client.get_full_name()} - {self.plan.name}"
    
    def set_remaining_sessions(self):
        if self.plan.access_type == "fixed_sessions":
            self.remaining_sessions = self.plan.access_value
            reserved = self.reservations.filter(cancelled_at__isnull=True).count()
            self.remaining_sessions -= reserved
        else:
            self.remaining_sessions = None

        self.save(update_fields=["remaining_sessions"])
    
    def get_payments(self):
        return self.payments.filter(status="paid")
    
    def get_total_paid(self):
        total = 0
        for payment in self.get_payments():
            total += payment.amount
        
        return total

    def is_paid(self):
        return self.plan.price <= self.get_total_paid()

    def set_status(self):
        today = timezone.now() 
        if self.expiration_date < today.date():
            self.is_active = False
            self.cancelled_at = today
            self.cancellation_comments = "Cancelación automática"
    
    @cached_property
    def expiration_date(self):
        return self.get_expiration_date()

    def get_expiration_date(self):
        if self.plan.validity_type == "no_expiry":
            return None
        ref_date = self.first_use_date or self.purchase_date
        return self.plan.get_expiry_date(ref_date)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
    
    def plan_expiry_description(self):
        expiry = self.get_expiration_date()
        if expiry:
            days = (expiry - date.today()).days
            return f"{self.plan.name} (expira en {days} días)"
        
        return f"{self.plan.name} (sin vencimiento)"

class ClientPushToken(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    token = models.CharField(max_length=255, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

backend/clients/views.py
from django.contrib.auth.decorators import login_required
from utils.functions import list_view
from .models import *
from .forms import *
from django.utils.translation import gettext_lazy as _
from utils.functions import render_to
from core.forms import FiltroForm
from django.shortcuts import redirect
from django.contrib import messages
from django.db.models import Q
from utils.functions import get_tenant
from django.utils import timezone
from django.template.loader import render_to_string
from django.urls import reverse
from django.http import JsonResponse
from payments.models import Payment

@login_required
def clients(request):
    objects = Client.objects.all()
    form = FiltroForm(request.GET or None)

    if form.is_valid():
        q = form.cleaned_data.get('q')
        fecha_desde = form.cleaned_data.get('fecha_desde')
        fecha_hasta = form.cleaned_data.get('fecha_hasta')

        if q:
            objects = objects.filter(
                Q(first_name__icontains=q) | 
                Q(last_name__icontains=q)
            )

        if fecha_desde:
            objects = objects.filter(created_at__gte=fecha_desde)

        if fecha_hasta:
            objects = objects.filter(created_at__lte=fecha_hasta)

    return list_view(
        request,
        objects,
        "clients/clients.html",
        {
            "title": "Clientes",
            "filtro_form": form,
        },
    )

@login_required
def delete_client(request, pk):
    instance = Client.objects.get(pk=pk)
    instance.user_obj.companies.filter(company=get_tenant()).delete()
    instance.user.delete()
    instance.delete()
    messages.success(request, "Los datos han sido guardados correctamente")
    return redirect('clients:clients') 

@login_required
def client(request, pk=None):
    title = "Agregar cliente"
    instance = Client(created_by=request.user, source='admin_panel')

    if pk:
        instance = Client.objects.get(pk=pk)
        title = f"Editar cliente: {instance.get_full_name()}"
    
    if request.method == 'POST':
        form = ClientForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():

            form.instance.updated_by = request.user
            form.save()
            current_plan = form.instance.current_plan
            
            plan = form.cleaned_data.get("plan")

            if current_plan and form.cleaned_data.get("cancel_current_plan"):
                current_plan.cancelled_at = timezone.now()
                current_plan.cancelled_by = request.user
                current_plan.cancellation_comments = f"Cancelado desde editar cliente"
                current_plan.is_active = False
                current_plan.save()
                current_plan = None
                plan = None

            if plan and not current_plan:
                client_plan = ClientPlan(
                    client=form.instance,
                    plan=plan,
                    purchase_date=timezone.now(),
                    created_by=request.user,
                )
                client_plan.save()
                
            messages.success(request, "Los datos han sido guardados correctamente")
            
            if request.POST.get("redirect_back"):
                return redirect(".")
            
            return redirect('clients:clients') 
        messages.error(request, "Corrija los errores para continuar")
    else:
        form = ClientForm(instance=instance)

    context = {
        "title": title,
        "form": form
    }
    return render_to(request, "clients/client.html", context)

@login_required
def save_client_plan_payment(request, client_plan_pk):
    client_plan = ClientPlan.objects.get(pk=client_plan_pk)
    if client_plan.is_paid():
        messages.error(request, "El plan ya se encuentra pagado")
        return redirect("/")
    
    instance = None
    form = ClientPlanPaymentForm(request.POST, request.FILES, instance=instance)
    back_url = request.POST.get("back_url")

    if form.is_valid():
        form.instance.client_plan = client_plan
        form.instance.method = "manual"
        form.instance.created_by = request.user
        if form.instance.status == "paid":
            form.instance.paid_at = timezone.now()
        
        form.save()
        return redirect(back_url)
    
    messages.error(request, "Corrija los errores para continuar")
    return redirect(back_url)

@login_required
def get_client_plan_payment_form(request, client_plan_pk):
    client_plan = ClientPlan.objects.get(pk=client_plan_pk)
    instance = Payment(
        client_plan=client_plan,
        amount=client_plan.plan.price,
        status='paid',
        method='manual',
    )
    form = ClientPlanPaymentForm(instance=instance)
    html = render_to_string(
        "clients/client_plan_payment_form.html", 
        {
            "form": form, 
            "action_url": reverse("clients:save_client_plan_payment", args=[client_plan_pk]),
            "back_url": request.GET.get("back_url")
        },
        request=request
    )
    return JsonResponse({
        "html": html
    })

backend/clients/templates/clients/client.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<form method="post" novalidate>
  {% csrf_token %}
  <div class="page-body">
    <div class="container-xl">
      <div class="row">
        <div class="col-md-8">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">{{ title }}</h3>
            </div>
            <div class="card-body">
                <h4 class="mb-3">Cuenta de usuario</h4>
                <div class="row g-3">
                  <div class="col-md-6">
                    <label for="{{ form.username.id_for_label }}" class="form-label">Email</label>
                    {{ form.email }}
                    {% if form.email.errors %}
                      <div class="invalid-feedback d-block">{{ form.email.errors }}</div>
                    {% endif %}
                  </div>
      
                  <div class="col-md-6">
                    <label for="{{ form.password.id_for_label }}" class="form-label">Contraseña</label>
                    {{ form.password }}
                    {% if form.password.errors %}
                      <div class="invalid-feedback d-block">{{ form.password.errors }}</div>
                    {% endif %}
                  </div>
                </div>
                <!-- Sección: Datos del cliente -->
                <h4 class="mt-5 mb-3">Datos personales</h4>
                <div class="row g-3">
                  <div class="col-md-6">
                    <label for="{{ form.first_name.id_for_label }}" class="form-label">Nombre</label>
                    {{ form.first_name }}
                    {% if form.first_name.errors %}
                      <div class="invalid-feedback d-block">{{ form.first_name.errors }}</div>
                    {% endif %}
                  </div>
      
                  <div class="col-md-6">
                    <label for="{{ form.last_name.id_for_label }}" class="form-label">Apellido</label>
                    {{ form.last_name }}
                    {% if form.last_name.errors %}
                      <div class="invalid-feedback d-block">{{ form.last_name.errors }}</div>
                    {% endif %}
                  </div>
      
                  <div class="col-md-4">
                    <label for="{{ form.phone.id_for_label }}" class="form-label">Teléfono</label>
                    {{ form.phone }}
                    {% if form.phone.errors %}
                      <div class="invalid-feedback d-block">{{ form.phone.errors }}</div>
                    {% endif %}
                  </div>
      
                  <div class="col-md-8">
                    <div class="mb-3">
                      <label class="form-label">Fecha de nacimiento</label>
                      <div class="row g-2">
                        <div class="col-5">
                          {{ form.birth_day }}
                          {{ form.birth_day.errors }}
                        </div>
                        <div class="col-3">
                          {{ form.birth_month }}
                          {{ form.birth_month.errors }}
                        </div>
                        <div class="col-4">
                          {{ form.birth_year }}
                          {{ form.birth_year.errors }}
                        </div>
                      </div>
                      {{ form.birth_date.errors }}
                    </div>
                  </div>
                </div>
      
                <div class="text-end pt-3">
                  <button name="redirect_back" value="1" type="submit" class="btn btn-ghost btn-primary">Guardar y seguir editando</button>
                  <button type="submit" class="btn btn-primary">Guardar</button>
                </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          {% if form.instance.id %}
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Plan</h3>
            </div>

            {% if form.instance.current_plan %}
              <div class="list-group list-group-flush list-group-hoverable">
                  <div class="list-group-item list-group-item-action active">
                    <div class="fw-bold">{{ form.instance.current_plan.plan_expiry_description }}</div>
                    <div>Asignado el {{ form.instance.current_plan.created_at }} por {{ form.instance.current_plan.created_by|default:"" }}</div>
                    <div class="d-flex flex-wrap align-items-center mt-2">
                      
                      {% if not form.instance.current_plan.is_paid %}
                      <a href="#" data-url="{% url 'clients:get_client_plan_payment_form' form.instance.current_plan.pk %}?back_url={{ request.path }}" class="btn btn-ghost btn-success me-2 client-plan-payment-form">Capturar pago</a>
                      {% endif %}
                      <div>
                        <label class="form-check m-0">
                          {{ form.cancel_current_plan }}
                          <span class="form-check-label fw-bold text-danger">Cancelar plan</span>
                        </label>
                      </div>
                    </div>
                  </div>
              </div>
              {% endif %}

              {% if not form.instance.current_plan %}
              <div class="card-body">
                <div class="row">
                  <div class="mb-3">
                    <div class="form-selectgroup form-selectgroup-boxes d-flex">
                      {% for radio in form.plan %}
                        <label class="form-selectgroup-item flex-fill">
                          <input
                            type="radio"
                            name="{{ form.plan.name }}"
                            value="{{ radio.data.value }}"
                            id="{{ radio.id_for_label }}"
                            {% if radio.data.selected %}checked{% endif %}
                            class="form-selectgroup-input"
                          >
                          <div class="form-selectgroup-label d-flex align-items-center p-3">
                            <div class="me-3">
                              <span class="form-selectgroup-check"></span>
                            </div>
                            <div>
                              <strong>{{ radio.choice_label }}</strong><br>
                            </div>
                          </div>
                        </label>
                      {% endfor %}
                    </div>
                  </div>
                </div>
              </div>
              {% endif %}

            <div class="card-header">
              <h3 class="card-title">Historial de contrataciones</h3>
            </div>
            <div class="list-group list-group-flush list-group-hoverable" style="max-height: 500px; overflow-y: auto;">
              {% for client_plan in form.instance.get_plans_history %}
              <div class="list-group-item">
                <div class="fw-bold">{{ client_plan.plan }} ({{ client_plan.purchase_date|date:"d F Y" }} a {{ client_plan.expiration_date|date:"d F Y" }})</div>
                <div class="text-sm text-danger lh-sm">
                  <div>Cancelado el <b>{{ client_plan.cancelled_at|date:"d/m/Y H:i" }}</b> {% if client_plan.cancelled_by %}por {{ client_plan.cancelled_by|default:"" }}{% endif %}</div>
                  {% if client_plan.cancellation_comments %}
                  <p class="fst-italic py-1 m-0">{{ client_plan.cancellation_comments }}</p>
                  {% endif %}
                </div>
                  
              </div>
              {% endfor %}
            </div>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</form>

<div class="modal modal-blur fade rounded" id="modal_client_plan_form" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
    <div class="modal-content">
        <div id="modal_form"></div>
    </div>
  </div>
</div>

  <script>
document.addEventListener('DOMContentLoaded', function () {
  document.body.addEventListener('click', async function (event) {
    const target = event.target.closest('.client-plan-payment-form');

    if (target) {
      event.preventDefault();  // Evita el salto por href="#"
      const url = target.getAttribute('data-url');

      try {
        const response = await fetch(url, {
          headers: {
            // 'X-Requested-With': 'XMLHttpRequest',
            'X-CSRFToken': getCookie('csrftoken'),
          },
        });

        if (!response.ok) throw new Error('Error en la respuesta');

        const data = await response.json(); // Se espera JSON con una clave `html`
        document.getElementById('modal_form').innerHTML = data.html;
        const modalEl = document.getElementById('modal_client_plan_form');
        const bsModal = new tabler.bootstrap.Modal(modalEl);
        bsModal.show();
      } catch (error) {
        console.error('Error al cargar el formulario:', error);
        alert('Hubo un problema al cargar el formulario.');
      }
    }
  });
});
</script>
{% endblock %}

backend/clients/templates/clients/clients.html
{% extends "core/base.html" %}

{% block panel_header %}
<div class="page-header d-print-none text-white" aria-label="Page header">
    <div class="container-xl">
      <div class="row g-2 align-items-center">
        <div class="col">
          <!-- Page pre-title -->
          <h2 class="page-title">{{ title }}</h2>
          <div class="page-pretitle">Administra tus clientes</div>
        </div>
        <!-- Page title actions -->
        <div class="col-auto ms-auto d-print-none">
          <div class="btn-list">
            <a href="{% url 'clients:client' %}" class="btn btn-primary btn-5 d-none d-sm-inline-block">
              <!-- Download SVG icon from http://tabler.io/icons/icon/plus -->
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-2">
                <path d="M12 5l0 14"></path>
                <path d="M5 12l14 0"></path>
              </svg>
              Agregar cliente
            </a>
          </div>
          <!-- BEGIN MODAL -->
          <!-- END MODAL -->
        </div>
      </div>
    </div>
  </div>
{% endblock panel_header %}

{% block content %}
  <div class="row row-cards">
    <div class="col-12">
      {% if not list.object_list %}
        {% include "utils/empty_state.html" with create_url=crear_cliente_url %}
      {% else %}
      <div class="card">
        <div class="card-table">
          <div class="card-header">
            <div class="row w-full">
              <div class="col-md-12">
                <div class="ms-auto d-flex flex-wrap btn-list">
                  <form action="." class="ms-auto d-flex flex-wrap align-items-start btn-list">
                    <input type="hidden" name="f" value="1">

                    <div class="input-group input-group-flat w-auto">
                      <span class="input-group-text">
                        <!-- Download SVG icon from http://tabler.io/icons/icon/search -->
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-1">
                          <path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"></path>
                          <path d="M21 21l-6 -6"></path>
                        </svg>
                      </span>
                      {{ filtro_form.q }}
                      {{ filtro_form.errors }}
                      <span class="input-group-text">
                        <kbd>ctrl + K</kbd>
                      </span>
                    </div>

                    <div class="input-group input-group-flat w-auto">
                      <span class="input-group-text px-2">Elem. por página</span>
                      {{ filtro_form.page_size }}
                    </div>

                    <button type="submit" class="btn btn-outline-primary btn-icon">
                    <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-filter"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 4h16v2.172a2 2 0 0 1 -.586 1.414l-4.414 4.414v7l-6 2v-8.5l-4.48 -4.928a2 2 0 0 1 -.52 -1.345v-2.227z" /></svg>
                    </button>

                    {% if request.GET.f %}
                    <a href="{{ request.path }}" class="btn btn-danger btn-icon" data-bs-toggle="tooltip" title="Limpiar filtros">
                    <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-filter-x"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M13.758 19.414l-4.758 1.586v-8.5l-4.48 -4.928a2 2 0 0 1 -.52 -1.345v-2.227h16v2.172a2 2 0 0 1 -.586 1.414l-4.414 4.414v1.5" /><path d="M22 22l-5 -5" /><path d="M17 22l5 -5" /></svg>
                    </a>
                    {% endif %}
                  </form>
                </div>
              </div>
            </div>
          </div>
          <div id="advanced-table">
            <div class="table-responsive">
              <table class="table table-vcenter table-selectable">
                <thead>
                  <tr>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Plan</th>
                    <th>Creado</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody class="table-tbody">
                  {% for obj in list.object_list %}
                  <tr>
                    <td>{{ obj.get_full_name }}</td>
                    <td>{{ obj.email|default:'' }}</td>
                    <td>
                      {% if obj.current_plan %}
                      <span class="badge bg-info-lt" data-bs-toggle="tooltip" title="Fecha de expiración: {{ obj.current_plan.expiration_date|date:'d/m/Y' }}">{{ obj.current_plan.plan_expiry_description }}</span>
                      
                      <div class="my-1">
                      {% if obj.current_plan.is_paid %}
                        <span class="badge bg-success-lt"><svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-receipt-dollar"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M5 21v-16a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v16l-3 -2l-2 2l-2 -2l-2 2l-2 -2l-3 2" /><path d="M14.8 8a2 2 0 0 0 -1.8 -1h-2a2 2 0 1 0 0 4h2a2 2 0 1 1 0 4h-2a2 2 0 0 1 -1.8 -1" /><path d="M12 6v10" /></svg> Pagado</span>
                      {% else %}
                        <span class="badge bg-danger-lt"><svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-receipt-dollar"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M5 21v-16a2 2 0 0 1 2 -2h10a2 2 0 0 1 2 2v16l-3 -2l-2 2l-2 -2l-2 2l-2 -2l-3 2" /><path d="M14.8 8a2 2 0 0 0 -1.8 -1h-2a2 2 0 1 0 0 4h2a2 2 0 1 1 0 4h-2a2 2 0 0 1 -1.8 -1" /><path d="M12 6v10" /></svg> Pendiente de pago</span>
                      {% endif %}
                      </div>
                        
                      {% else %}
                      <span class="badge bg-danger-lt">Sin plan</span>
                      {% endif %}
                    </td>
                    <td>
                      {{ obj.created_at }}
                      <small class="d-block text-muted">(Desde {{ obj.get_source_display }})</small>
                    </td>
                    <td>
                      <div class="btn-list flex-nowrap justify-content-end">
                        <a href="{% url 'clients:client' obj.id %}"> Editar</a>
                        <a data-confirm="¿Estás seguro que deseas eliminar este registro?" class="text-danger" href="{% url 'clients:delete_client' obj.id %}"> Eliminar</a>
                      </div>
                    </td>
                  </tr>
                  {% endfor %}  
                </tbody>
              </table>
            </div>
            <div class="card-footer">
             {% include 'utils/pagination.html' %}
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
{% endblock %}