backend/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)


# Importa tus viewsets aquí
# from api.views.auth import RegisterView, LoginView, LogoutView, ProfileView
# from api.views.plans import PlanViewSet
# from api.views.classes import ClassViewSet
# from api.views.messages import MessageViewSet

router = DefaultRouter()
router.register(r'plans', views.PlanViewSet, basename='plan')
router.register(r'push_tokens', views.ClientPushTokenViewSet, basename='push_tokens')
# router.register(r'classes', ClassViewSet, basename='class')
# router.register(r'messages', MessageViewSet, basename='message')

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('create_checkout_link/', views.create_checkout_link, name='create_checkout_link'),
    path('user/dashboard/', views.user_dashboard, name='user_dashboard'),
    path('company_info/', views.company_info, name='company_info'),
    path('classes/', views.classes, name='classes'),
    path('reservations/', views.reservations, name='reservations'),
    path('reservations/<int:id>/check_in/', views.reservation_check_in, name='reservation_check_in'),
    path('reservations/<int:id>/cancel/', views.reservation_cancel, name='reservation_cancel'),
    path('account/reservations/', views.account_reservations, name='account_reservations'),
    path('sessions/<int:activity_session_id>/book/', views.activity_session_book, name='activity_session_book'),
    path('sessions/<int:activity_session_id>/waitlist/', views.activity_session_waitlist, name='activity_session_waitlist'),

    # Rutas automáticas de los routers (planes, clases, mensajes, etc.)
    path('', include(router.urls)),
]

backend/backend/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('', include('core.urls')),
    path("activities/", include("activities.urls", namespace="activities")),
    path("staff/", include("staff.urls", namespace="staff")),
    path("clients/", include("clients.urls", namespace="clients")),
    path("plans/", include("plans.urls", namespace="plans")),
    path("payments/", include("payments.urls", namespace="payments")),
    path("locations/", include("locations.urls", namespace="locations")),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    # path('sh/', include('sh.urls')),
]

backend/payments/urls.py
app_name = "payments"

from django.urls import path
from . import views

urlpatterns = [
    path("payments/", views.payments, name="payments"),
    path("payment/<int:pk>/", views.payment, name="payment"),
    path("stripe_payment/success/", views.stripe_payment_success, name="stripe_payment_success"),
    path("stripe_payment/cancel/", views.stripe_payment_cancel, name="stripe_payment_cancel"),
    path("stripe_webhook/", views.stripe_webhook, name="stripe_webhook"),
]

backend/payments/models.py
# payments/models.py
from django.db import models
from core.models import BaseModel
from clients.models import ClientPlan
from django.utils.functional import cached_property

class Payment(BaseModel):
    PAYMENT_METHODS = [
        ('stripe', 'Stripe'),
        ('cash', 'Efectivo'),
        ('paypal', 'PayPal'),
        ('manual', 'Manual'),
    ]

    STATUS_CHOICES = [
        ('pending', 'Pendiente'),
        ('paid', 'Pagado'),
        ('failed', 'Fallido'),
        ('cancelled', 'Cancelado'),
    ]

    client_plan = models.ForeignKey(ClientPlan, on_delete=models.CASCADE, null=True, related_name="payments")
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    method = models.CharField(max_length=20, choices=PAYMENT_METHODS)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    transaction_id = models.CharField(max_length=100, blank=True, null=True)  
    metadata = models.JSONField(blank=True, null=True)

    cancelled_at = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    paid_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']

    @cached_property
    def client(self):
        if self.client_plan:
            return self.client_plan.client
        
    @cached_property
    def plan(self):
        if self.client_plan:
            return self.client_plan.plan

backend/payments/forms.py
from core.forms import FormControlMixin
from django import forms
from .models import *

class PaymentForm(FormControlMixin, forms.ModelForm):
    class Meta:
        model = Payment
        fields = [
            "client_plan",
            "amount",
            "method",
            "status",
            "transaction_id",
        ]

backend/payments/views.py
from django.contrib.auth.decorators import login_required
from utils.functions import list_view
from .models import *
from .forms import *
from utils.functions import render_to
from core.forms import FiltroForm
from django.shortcuts import redirect
from django.contrib import messages
from django.conf import settings
from plans.models import Plan
from clients.models import Client, ClientPlan
from django.http import HttpResponseBadRequest, HttpResponse
from django.views.decorators.csrf import csrf_exempt
import stripe
from django.utils import timezone


@login_required
def payments(request):
    objects = Payment.objects.all().prefetch_related("client_plan__client", "client_plan__plan")
    form = FiltroForm(request.GET or None)

    if form.is_valid():
        fecha_desde = form.cleaned_data.get('fecha_desde')
        fecha_hasta = form.cleaned_data.get('fecha_hasta')

        if fecha_desde:
            objects = objects.filter(created_at__gte=fecha_desde)

        if fecha_hasta:
            objects = objects.filter(created_at__lte=fecha_hasta)

    return list_view(
        request,
        objects,
        "payments/payments.html",
        {
            "title": "Historial de pagos",
            "filtro_form": form,
        },
    )

@login_required
def payment(request, pk=None):
    title = "Agregar pago"
    instance = Payment(created_by=request.user)
    if pk:
        instance = Payment.objects.get(pk=pk)
        title = f"Editar pago: {instance.client}"
    
    if request.method == 'POST':
        form = PaymentForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.instance.updated_by = request.user
            form.save()
            messages.success(request, "Los datos han sido guardados correctamente")
            return redirect('payments:payments') 
        messages.error(request, "Corrija los errores para continuar")
    else:
        form = PaymentForm(instance=instance)

    context = {
        "title": title,
        "form": form
    }
    return render_to(request, "payments/payment.html", context)

def stripe_payment_success(request):
    magic_link = f"muvon://payment-success"
    return redirect(magic_link)
    return HttpResponse({"success": True, "magic_link": magic_link})

def stripe_payment_cancel(request):
    magic_link = f"muvon://payment-cancel"
    return redirect(magic_link)
    return HttpResponse({"success": True, "magic_link": magic_link})

@csrf_exempt
def stripe_webhook(request):

    if not request.tenant.settings.stripe_enabled:
        return HttpResponse(status=200)

    stripe.api_key = request.tenant.settings.stripe_secret_key
    webhook_secret = request.tenant.settings.stripe_webhook_secret

    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']

    try:
        event = stripe.Webhook.construct_event(payload, sig_header, webhook_secret)
    except (ValueError, stripe.error.SignatureVerificationError) as e:
        return HttpResponseBadRequest(str(e))

    if event['type'] == 'checkout.session.completed':
        session = event['data']['object']
        metadata = session['metadata']
        client_id = metadata.get('client_id')
        plan_id = metadata.get('plan_id')
        session_id = session['id']

        # Activar plan
        client_plan = ClientPlan.objects.filter(
            client_id=client_id,
            plan_id=plan_id,
            stripe_session_id=session_id
        ).first()

        if client_plan:
            client_plan.is_active = True
            client_plan.purchase_date = timezone.now()
            client_plan.save()
        else:
            # fallback si no se guardó antes
            client_plan = ClientPlan.objects.create(
                client_id=client_id,
                plan_id=plan_id,
                stripe_session_id=session_id,
                is_active=True,
                paid_at=timezone.now()
            )
        
        Payment.objects.create(
            client_plan=client_plan,
            amount=(session.get('amount_total', 0) or 0) / 100,  # Stripe da en centavos
            method='stripe',
            status='paid',
            transaction_id=session.get('payment_intent'),
            paid_at=timezone.now(),
        )

    return HttpResponse(status=200)

backend/payments/templates/payments/payment.html
{% extends "core/base.html" %}
{% load static %}
{% block content %}
<div class="container py-4">
  <div class="row">
    <div class="col-lg-10 mx-auto">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">{{ title }}</h3>
        </div>
        <form method="post" novalidate>
          {% csrf_token %}
          <div class="card-body">
            {{ form }}
          </div>
          <div class="card-footer text-end">
            <button type="submit" class="btn btn-primary">Guardar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

  

backend/payments/templates/payments/payments.html
{% extends "core/base.html" %}

{% block panel_header %}
<div class="page-header d-print-none text-white" aria-label="Page header">
    <div class="container-xl">
      <div class="row g-2 align-items-center">
        <div class="col">
          <!-- Page pre-title -->
          <h2 class="page-title">{{ title }}</h2>
        </div>
        <!-- Page title actions -->
        <div class="col-auto ms-auto d-print-none">
          <!-- <div class="btn-list">
            <a href="#" class="btn btn-primary btn-5 d-none d-sm-inline-block">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-2">
                <path d="M12 5l0 14"></path>
                <path d="M5 12l14 0"></path>
              </svg>
              Agregar pago
            </a>
          </div> -->
        </div>
      </div>
    </div>
  </div>
{% endblock panel_header %}

{% block content %}
  <div class="row row-cards">
    <div class="col-12">
      {% if not list.object_list %}
        {% include "utils/empty_state.html" with create_url=crear_cliente_url %}
      {% else %}
      <div class="card">
        <div class="card-table">
          <div class="card-header">
            <div class="row w-full">
              <div class="col-md-12">
                <div class="ms-auto d-flex flex-wrap btn-list">
                  <form action="." class="ms-auto d-flex flex-wrap align-items-start btn-list">
                    <input type="hidden" name="f" value="1">

                    <div class="input-group input-group-flat w-auto">
                      <span class="input-group-text">
                        <!-- Download SVG icon from http://tabler.io/icons/icon/search -->
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-1">
                          <path d="M10 10m-7 0a7 7 0 1 0 14 0a7 7 0 1 0 -14 0"></path>
                          <path d="M21 21l-6 -6"></path>
                        </svg>
                      </span>
                      {{ filtro_form.q }}
                      {{ filtro_form.errors }}
                      <span class="input-group-text">
                        <kbd>ctrl + K</kbd>
                      </span>
                    </div>

                    <div class="input-group input-group-flat w-auto">
                      <span class="input-group-text px-2">Elem. por página</span>
                      {{ filtro_form.page_size }}
                    </div>

                    <button type="submit" class="btn btn-outline-primary btn-icon">
                    <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-filter"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 4h16v2.172a2 2 0 0 1 -.586 1.414l-4.414 4.414v7l-6 2v-8.5l-4.48 -4.928a2 2 0 0 1 -.52 -1.345v-2.227z" /></svg>
                    </button>

                    {% if request.GET.f %}
                    <a href="{{ request.path }}" class="btn btn-danger btn-icon" data-bs-toggle="tooltip" title="Limpiar filtros">
                    <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-filter-x"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M13.758 19.414l-4.758 1.586v-8.5l-4.48 -4.928a2 2 0 0 1 -.52 -1.345v-2.227h16v2.172a2 2 0 0 1 -.586 1.414l-4.414 4.414v1.5" /><path d="M22 22l-5 -5" /><path d="M17 22l5 -5" /></svg>
                    </a>
                    {% endif %}
                  </form>
                </div>
              </div>
            </div>
          </div>
          <div id="advanced-table">
            <div class="table-responsive">
              <table class="table table-vcenter table-selectable">
                <thead>
                  <tr>
                    <th>Cliente</th>
                    <th>Status</th>
                    <th>Método</th>
                    <th>Plan</th>
                    <th class="text-end">Importe</th>
                    <th>Creado</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody class="table-tbody">
                  {% for obj in list.object_list %}
                  <tr>
                    <td class="fw-bold">{{ obj.client.get_full_name }}</td>
                    <td>{{ obj.get_status_display }}</td>
                    <td>{{ obj.get_method_display }}</td>
                    <td>{{ obj.plan.name }}</td>
                    <td class="text-end">${{ obj.amount }}</td>
                    <td>{{ obj.created_at }}</td>
                    <td>
                      <div class="btn-list flex-nowrap justify-content-end">
                        <a href="{% url 'payments:payment' obj.id %}"> Editar</a>
                      </div>
                    </td>
                  </tr>
                  {% endfor %}  
                </tbody>
              </table>
            </div>
            <div class="card-footer">
             {% include 'utils/pagination.html' %}
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    </div>
  </div>
{% endblock %}
  